const ClassroomActionTypes = {
  FETCH_A_CLASSROOM_REQUEST: "FETCH_A_CLASSROOM_REQUEST",
  FETCH_A_CLASSROOM_SUCCESS: "FETCH_A_CLASSROOM_SUCCESS",
  FETCH_A_CLASSROOM_FAILURE: "FETCH_A_CLASSROOM_FAILURE",
  CLOSE_CLASSROOM: "CLOSE_CLASSROOM",
  CREATE_A_CLASSROOM_REQUEST: "CREATE_A_CLASSROOM_REQUEST",
  CREATE_A_CLASSROOM_SUCCESS: "CREATE_A_CLASSROOM_SUCCESS",
  CREATE_A_CLASSROOM_FAILURE: "CREATE_A_CLASSROOM_FAILURE",
  UPDATE_CLASSROOM_REQUEST: "UPDATE_CLASSROOM_REQUEST",
  UPDATE_CLASSROOM_SUCCESS: "UPDATE_CLASSROOM_SUCCESS",
  UPDATE_CLASSROOM_FAILURE: "UPDATE_CLASSROOM_FAILURE",
  UPLOAD_STUDENT_LIST_REQUEST: "UPLOAD_STUDENT_LIST_REQUEST",
  UPLOAD_STUDENT_LIST_SUCCESS: "UPLOAD_STUDENT_LIST_SUCCESS",
  UPLOAD_STUDENT_LIST_FAILURE: "UPLOAD_STUDENT_LIST_FAILURE",
  UPLOAD_GRADE_FOR_AN_ASSIGNMENT_REQUEST:
    "UPLOAD_GRADE_FOR_AN_ASSIGNMENT_REQUEST",
  UPLOAD_GRADE_FOR_AN_ASSIGNMENT_SUCCESS:
    "UPLOAD_GRADE_FOR_AN_ASSIGNMENT_SUCCESS",
  UPLOAD_GRADE_FOR_AN_ASSIGNMENT_FAILURE:
    "UPLOAD_GRADE_FOR_AN_ASSIGNMENT_FAILURE",
  GET_GRADES_BY_CLASSROOM_REQUEST: "GET_GRADES_BY_CLASSROOM_REQUEST",
  GET_GRADES_BY_CLASSROOM_SUCCESS: "GET_GRADES_BY_CLASSROOM_SUCCESS",
  GET_GRADES_BY_CLASSROOM_FAILURE: "GET_GRADES_BY_CLASSROOM_FAILURE",
};

export default ClassroomActionTypes;
