const ClassroomsActionTypes = {
  FETCH_CLASSROOMS_REQUEST: "FETCH_CLASSROOMS_REQUEST",
  FETCH_CLASSROOMS_SUCCESS: "FETCH_CLASSROOMS_SUCCESS",
  FETCH_CLASSROOMS_FAILURE: "FETCH_CLASSROOMS_FAILURE",
  CLEAR_CLASSROOMS: "CLEAR_CLASSROOMS",
  FETCH_A_CLASSROOM_REQUEST: "FETCH_A_CLASSROOM_REQUEST",
  FETCH_A_CLASSROOM_SUCCESS: "FETCH_A_CLASSROOM_SUCCESS",
  FETCH_A_CLASSROOM_FAILURE: "FETCH_A_CLASSROOM_FAILURE",
  JOIN_CLASSROOM_BY_INVITAION_CODE_REQUEST:
    "JOIN_CLASSROOM_BY_INVITAION_CODE_REQUEST",
  JOIN_CLASSROOM_BY_INVITAION_CODE_SUCCESS:
    "JOIN_CLASSROOM_BY_INVITAION_CODE_SUCCESS",
  JOIN_CLASSROOM_BY_INVITAION_CODE_FAILURE:
    "JOIN_CLASSROOM_BY_INVITAION_CODE_FAILURE",
  CREATE_INVITATION_REQUEST: "CREATE_INVITATION_REQUEST",
  CREATE_INVITATION_SUCCESS: "CREATE_INVITATION_SUCCESS",
  CREATE_INVITATION_FAILURE: "CREATE_INVITATION_FAILURE",
};

export default ClassroomsActionTypes;
